### PR TITLE
Use only one Server

### LINKED ISSUE #75: (1) Utilizar apenas um servidor
- Remover os radio buttons de escolha de server da InitialScreen
    - InitialScreen vai se conectar ao "production" por padrão
    - Dar algum jeito de conectar ao localhost em ambiente de dev
    - Trocar "connect to server" pra "Play!"

### PR DESCRIPTION
**Pull request by aateg**
Closes #75 

- [x] Remove radio buttons from initial screen
- [x] InitialScreen connects to "production" by default
- [x] During development, automatically connects client to localhost Server
- [x] Change "Connect to server' to "Play!"

### CODE REVIEW

**Comment by aateg** [comment]
@rulojuka 
Commom configurations package failing to load file, tried changing to XML, couldn't find the answer to the problem

Please, insert a breakpoint at FileProperties at line 18.

**Comment by rulojuka** [comment]
It was not working here because the maven package is broken and we need to add other dependency manually :/
After that, the code worked perfectly!
Anyway, I am switching back to a text file, as I find that more easily maintainable

**Comment by rulojuka** [comment]
In fact, I will leave it that way for now!
Awesome job!!

**Comment by rulojuka** [comment]
Awesome job!! :+1: :+1:

**Pull request merged**
