### PR TITLE
[fix] Manual fix on several stylecheck errors

### PR DESCRIPTION
**Pull request by Yamaguti**
Please merge [PR 34](https://github.com/rulojuka/sbking/pull/34) before this one, since that PR introduces the style checker in mvn.

### CODE REVIEW

**Comment by Yamaguti** [comment]
For a cleaner file diff view, please select option "Hide whitespace changes" under the cog button :)

**Comment by rulojuka** [comment]
Approved! Thanks a lot!
If you'd like, I could resolve the conflicts, just push to a branch and I'll do the rest.

**Review by rulojuka — APPROVED** [review]

**Comment by rulojuka** [comment]
Btw, on the remaining errors:

NeedBraces: Dammit stupid eclipse snippet. I can fix that one by one.
MagicNumber: Good rule, I will try to fix that and maintain this type as an error
DesignForExtension: Probably not a thing to worry in our application. We should change at least change the severity to info.
HideUtilityClassConstructor: Good rule, I think it should be warning
VisibilityModifier: Good one, I should fix all of them.
FinalParameters: Hmm, this one I am a little uncertain. I think it should probably be a warning.
ModifierOrder: Easy to fix, good for maintenability. Will maintain that.
ConstantName: Good rule. To fix, basically change all "logger"s to "LOGGER"s.
LocalFinalVariableName: Hmm, I like those names on SBKingClient.java. Possibly they should be in another place (where both server and client can share it).
LocalVariableName: These should be on LocalFinalVariableName. I just forgot to make them final.
StaticVariableName: Maybe these have the same problem as the LocalFinalVariableName

**Comment by Yamaguti** [comment]
> Btw, on the remaining errors:

Agreed on the resolution of these errors.

I tried to solve most of formatting errors which were simple and some others like unused imports which I think are severe.

Will update checkstyle xml in a future PR, enforcing build breakage :)

**Comment by Yamaguti** [comment]
> Approved! Thanks a lot!
> If you'd like, I could resolve the conflicts, just push to a branch and I'll do the rest.

I've fixed the conflicts. Some new conde introduced since this PR was created added back a few minor style errors.

**Pull request merged**
