### PR TITLE
[feat] claim

### LINKED ISSUE #37: feat: claim
When a player make all next tricks it can claim that for the other players.
- User clicks the button "Claim all" tricks in any players turn
- Then a button appears to the opponents to "accept claim"
- All the remaing tricks are attributed to the claimer
- The deal is finished

### PR DESCRIPTION
**Pull request by aateg**
Closes #37

### CODE REVIEW

**Review by rulojuka — CHANGES_REQUESTED** [review]
It is not written on #37 but the person who asks for the claim will play with their (and their partner if it is a partnership game) open until the end of the deal.

**Comment by rulojuka** [comment]
Also, the accept claim button is doing nothing (tested on King)

**Comment by aateg** [comment]
> Also, the accept claim button is doing nothing (tested on King)
I tested here, and worked for King. Maybe it is usability problem. The idea is that one player claims, the opponents accept. And the last one to click the "Accept Claim" button needs to click on the any card after that. Seems logical for me, because they don't know if the patners accepted.

**Comment by aateg** [comment]
> It is not written on #37 but the person who asks for the claim will play with their (and their partner if it is a partnership game) open until the end of the deal.

ok, I'll add this feature.

**Pull request merged**
