### PR TITLE
[feat] adding Dev IP to server list

### PR DESCRIPTION
**Pull request by Yamaguti**

### CODE REVIEW

**Comment by rulojuka** [comment]
Could you please do this using a TextField? Commit ef5718fe6134d329de08b6ea6ab97f5761a94193 should help.

**Comment by Yamaguti** [comment]
> Could you please do this using a TextField? The removed code from [ef5718f](https://github.com/rulojuka/sbking/commit/ef5718fe6134d329de08b6ea6ab97f5761a94193) should help.
> Basically you could have 3 RadioButtons:
> 
> * [ ]  Taís
> * [ ]  Perez
> * [ ]  Other
>   [An empty text field]
> 
> If other is selected, then get hostname from text field. If none is selected, use localhost.

Instead, as we discussed offline, I moved all hard coded servers to the networkConfiguration.cfg, and removed the Map creation on getIpFromServer.

This PR also adds two TODOs that will be addressed in a future PR, regarding constants spread over the code (system exit values and the network config filename).

I've tested this change on all our three clients :)

**Comment by rulojuka** [comment]
@aateg I think you can review and merge this one!

**Review by aateg — APPROVED** [review]
Nice improvement @Yamaguti! I don't have anything to comment about the code, so I'm going to rebase and merge ;)

**Pull request merged**
